#!/usr/bin/env python3
#
# Generated SUPPORTED.md from the current definitions in the model library.

import logging

import coloredlogs
from jinja2 import Template
import argparse as arg

from pyavcontrol import DeviceModelLibrary

LOG = logging.getLogger(__name__)
coloredlogs.install(level="DEBUG")

def parse_args():
    p = arg.ArgumentParser(description="Generated SUPPORTED.md using current pyavcontrol model library")
    p.add_argument(
        "--output", default="SUPPORTED.md", help="output file"
    )
    p.add_argument(
        "--library", help="library directory"
    )
    p.add_argument("-d", "--debug", action="store_true", help="verbose logging")
    return p.parse_args()

def main():
    args = parse_args()
    
    library = DeviceModelLibrary.create()
    supported_models = library.supported_models()

    for model_id in supported_models:
        model_def = library.load_model(model_id)
        print(model_id)


if __name__ == "__main__":
    main()
